<?php
/**
 * Language labels for database tables/fields belonging to extension "pobdir"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"fe_users.tx_pobdir_directory" => "Is allowed to edit/create directory entries?",	
		"tx_pobdir_entry" => "Entry",	
		"tx_pobdir_entry.name" => "Name",	
		"tx_pobdir_entry.street" => "Street",	
		"tx_pobdir_entry.zip" => "ZIP-Code",	
		"tx_pobdir_entry.city" => "City",	
		"tx_pobdir_entry.tel" => "Telephone",	
		"tx_pobdir_entry.fax" => "Telefax",	 
		"tx_pobdir_entry.mobil" => "Mobile",
		"tx_pobdir_entry.email" => "Email",	
		"tx_pobdir_entry.www" => "Homepage",	
		"tx_pobdir_entry.profile" => "Profile",	
		"tx_pobdir_entry.image" => "Images (max 5)",	
		"tx_pobdir_entry.category" => "Category",
    "tx_pobdir_entry.map" => "Map",
    "tx_pobdir_entry.description" => "Description",
    "tx_pobdir_entry.features" => "Facilities",
    "tx_pobdir_entry.price" => "Price",
    "tx_pobdir_entry.priceinfo" => "Priceinfo",
    "tx_pobdir_entry.stars" => "Categorization",	
    "tx_pobdir_entry.capacity" => "Number of Persons",
    "tx_pobdir_entry.ads" => "Ads (1,3,4)",
    "tx_pobdir_entry.detail" => "Infopage allowed",
		"tx_pobdir_entry.belongsto" => "FE-User",		
		"tx_pobdir_entry.do_not_filter" => "Do Not Filter",
		"tx_pobdir_entry.mindestaufenthalt" => "Min. occupancy",
		"tx_pobdir_entry.pdf_info" => "PDF List Info",		
		"tx_pobdir_category" => "Category",	
		"tx_pobdir_category.name" => "Name",
		"tx_pobdir_ad" => "Ads",
    "tx_pobdir_ad.name" => "Name",	
		"tx_pobdir_ad.ad" => "Additional Texts (Ads)",		
		"tx_pobdir_feature" => "Features",
		"tx_pobdir_feature.name" => "Name",
		"tx_pobdir_feature.pikto" => "Filename",
		"tx_pobdir_feature.title" => "Mouseovertext",		
		"tx_pobdir_sperrzeiten" => "Blocked Dates",
    "tx_pobdir_sperrzeiten.entry_uid" => "Object-ID",
		"tx_pobdir_sperrzeiten.gesperrt_von" => "Blocked from",
		"tx_pobdir_sperrzeiten.gesperrt_bis" => "Blocked until",		
    "tx_pobdir_sperrzeiten.deleted" => "Inactive",		
		"tt_content.list_type" => "pobdir"	
	),
	"de" => Array (
		"fe_users.tx_pobdir_directory" => "Darf Verzeichniseinträge erstellen/editieren?",	
		"tx_pobdir_entry" => "Verzeichniseintrag",	
		"tx_pobdir_entry.name" => "Name",	
		"tx_pobdir_entry.street" => "Strasse",	
		"tx_pobdir_entry.zip" => "PLZ",	
		"tx_pobdir_entry.city" => "Stadt",	
		"tx_pobdir_entry.tel" => "Telefon",	
		"tx_pobdir_entry.fax" => "Telefax",
    "tx_pobdir_entry.mobil" => "Handy",	
		"tx_pobdir_entry.email" => "E-Mail",	
		"tx_pobdir_entry.www" => "Homepage",	
		"tx_pobdir_entry.profile" => "Profiltext",	
		"tx_pobdir_entry.image" => "Bilder  (max 5)",	
		"tx_pobdir_entry.category" => "Kategorie",    
    "tx_pobdir_entry.map" => "Lageplan",
    "tx_pobdir_entry.description" => "Beschreibung",
    "tx_pobdir_entry.features" => "Ausstattung",
    "tx_pobdir_entry.price" => "Preis",
    "tx_pobdir_entry.priceinfo" => "Preisinfo",
    "tx_pobdir_entry.stars" => "Klassifizierung",
    "tx_pobdir_entry.capacity" => "Anzahl Personen",    	
    "tx_pobdir_entry.ads" => "Werbetexte (z.B. 1,3,4)",
    "tx_pobdir_entry.detail" => "Detailseite erlauben",
		"tx_pobdir_entry.belongsto" => "Besitzer",    
    "tx_pobdir_entry.do_not_filter" => "Nicht filtern",
		"tx_pobdir_entry.mindestaufenthalt" => "Mindestaufenthalt",
		"tx_pobdir_entry.pdf_info" => "PDF Info",	
		"tx_pobdir_category" => "Eintrags-Kategorie",	
		"tx_pobdir_category.name" => "Name",
		"tx_pobdir_ad" => "Werbung",
    "tx_pobdir_ad.name" => "Name",   
		"tx_pobdir_ad.ad" => "Zusätzliche Texte (Werbung)", 		
		"tx_pobdir_feature" => "Ausstattung (Piktos)",
		"tx_pobdir_feature.name" => "Name",
		"tx_pobdir_feature.pikto" => "Dateiname des Piktograms",
		"tx_pobdir_feature.title" => "Beschreibung (Mouseover)",		
		"tx_pobdir_sperrzeiten" => "Sperrzeiten",
    "tx_pobdir_sperrzeiten.entry_uid" => "Objekt-ID",
		"tx_pobdir_sperrzeiten.gesperrt_von" => "Gesperrt von",
		"tx_pobdir_sperrzeiten.gesperrt_bis" => "Gesperrt bis",
		"tx_pobdir_sperrzeiten.deleted" => "Entfernen",		      		
		"tt_content.list_type" => "pobdir"	
	),
);
?>